collection:
  region: |
    WITH 
    bounds AS (
        SELECT ST_Extent(geom) AS geom FROM kart_pois.geom_ref WHERE id = 'geofence_active_mobility'
    ),
    merged_geometries AS (
        SELECT ST_Union(geom) AS geom
        FROM kart_pois.geom_ref
        WHERE id = 'geofence_active_mobility'
    ),
    grid AS (
        SELECT ST_MakeEnvelope(
            x::numeric, 
            y::numeric, 
            (x + 1)::numeric, 
            (y + 1)::numeric, 
            4326
        ) AS geom
        FROM generate_series(floor(ST_XMin((SELECT geom FROM bounds)))::integer, ceiling(ST_XMax((SELECT geom FROM bounds)))::integer, 1) AS x
        CROSS JOIN generate_series(floor(ST_YMin((SELECT geom FROM bounds)))::integer, ceiling(ST_YMax((SELECT geom FROM bounds)))::integer, 1) AS y
    ),
    intersections AS (
        SELECT 
            (ST_Dump(ST_Intersection(m.geom, ST_Buffer(g.geom, -0.00001)))).geom AS geom
        FROM merged_geometries m
        JOIN grid g ON ST_Intersects(m.geom, g.geom)
    )
    SELECT geom FROM intersections WHERE ST_GeometryType(geom) = 'ST_Polygon'

  source: s3a://overturemaps-us-west-2/release/2024-02-15-alpha.0/theme=places

preparation:

subscription: