preparation:
  region: | 
    WITH 
    bounds AS (
        SELECT ST_Extent(geom) AS geom FROM basic.geofence_active_mobility
    ),
    merged_geometries AS (
        SELECT ST_Union(geom) AS geom
        FROM basic.geofence_active_mobility
    ),
    grid AS (
        SELECT ST_MakeEnvelope(
            x::numeric, 
            y::numeric, 
            (x + 1)::numeric, 
            (y + 1)::numeric, 
            4326
        ) AS geom
        FROM generate_series(floor(ST_XMin((SELECT geom FROM bounds)))::integer, ceiling(ST_XMax((SELECT geom FROM bounds)))::integer, 1) AS x
        CROSS JOIN generate_series(floor(ST_YMin((SELECT geom FROM bounds)))::integer, ceiling(ST_YMax((SELECT geom FROM bounds)))::integer, 1) AS y
    ),
    intersections AS (
        SELECT 
            (ST_Dump(ST_Intersection(m.geom, ST_Buffer(g.geom, -0.00001)))).geom AS geom
        FROM merged_geometries m
        JOIN grid g ON ST_Intersects(m.geom, g.geom)
    )
    SELECT geom FROM intersections WHERE ST_GeometryType(geom) = 'ST_Polygon'

  classification:
    gtfs_route_types: 
      "0": "tram_stop"
      "1": "subway_entrance"
      "2": "rail_station"
      "3": "bus_stop"
      "100": "rail_station"
      "101": "rail_station"
      "102": "rail_station"
      "103": "rail_station"
      "105": "rail_station"
      "106": "rail_station"
      "109": "rail_station"
      "402": "subway_entrance"
      "700": "bus_stop"
      "704": "bus_stop"
      "715": "bus_stop"
      "900": "tram_stop"