# max 5 route types as we have 5 poi categories
preparation:
  region: 'SELECT ST_Subdivide(the_geom)::geometry AS geom FROM public."DEU_adm0";'
  classification:
    gtfs_route_types: 
      "0": "tram_stop"
      "1": "subway_entrance"
      "2": "rail_station"
      "3": "bus_stop"
      "100": "rail_station"
      "101": "rail_station"
      "102": "rail_station"
      "103": "rail_station"
      "105": "rail_station"
      "106": "rail_station"
      "109": "rail_station"
      "402": "subway_entrance"
      "700": "bus_stop"
      "704": "bus_stop"
      "715": "bus_stop"
      "900": "tram_stop"