version: "3.7"

networks:
  proxy:

volumes:
  db_data_preparation:

services:

  db:
    image: goat:db_data_preparation
    build: .
    container_name: db_data_preparation
    environment:
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=goat
      - DATABASE_URL=postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@goat_db:5432/goat
    volumes:
      - db_data_preparation:/var/lib/postgresql
      - .:/app
    ports:
      - "${POSTGRES_OUTER_PORT}:5432"
    restart: on-failure
    networks:
      proxy:
