version: "3.9"

networks:
  data_preparation_proxy:

volumes:
  db_data_preparation:

services:
  app:
    image: ${DOCKER_ID}/${COMPOSE_PROJECT_NAME}:app-${PROJECT_VERSION}
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: ${COMPOSE_PROJECT_NAME}_app
    env_file:
      - .env
    environment:
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_DBNAME=goat
      - PGDATABASE=goat
      - PGHOST=${COMPOSE_PROJECT_NAME}_db
      - DATABASE_URL=postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@goat_db:5432/goat
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    volumes:
      - .:/app
    networks:
      data_preparation_proxy:

  db:
    image: goatcommunity/database:test-release
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - POSTGRES_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=goat
      - DATABASE_URL=postgis://${POSTGRES_USER}:${POSTGRES_PASSWORD}@goat_db:5432/goat
    volumes:
      - db_data_preparation:/var/lib/postgresql
      - .:/app
    ports:
      - "${POSTGRES_OUTER_PORT}:5432"
    restart: on-failure
    networks:
      data_preparation_proxy:
