preparation:
  # Currently, the preparation script only reads segments from temporal.segments and writes the output to basic.segment
  # Currently, the preparation script only reads connectors from temporal.connectors and writes the output to basic.connector

  # A SQL query which returns the region's bounding geometry (omit terminating semicolon)
  region: "SELECT ST_Union(geom) AS geom FROM poi.geom_ref WHERE id = 'geofence_active_mobility'"

  # Coefficients specifying the cost of cycling on various surfaces
  cycling_surfaces:
    paving_stones: '0.2'
    unpaved: '0.2'
    gravel: '0.3'
    dirt: '0.4'
