region_pbf: [""]

collection:
  osm_tags:
    building: [True]
  additional_columns:
    [
      "amenity",
      "leisure",
      "addr:street",
      "addr:housenumber",
      "building:levels",
      "roof:levels",
    ]
  nodes: False
  ways: True
  relations: False

preparation:
  average_building_levels: 3
  average_roof_levels: 1

  classification:
    residential_status:

      polygon:
        landuse:
          query: 'SELECT geom 
                  FROM temporal.bologna_landuse 
                  WHERE cod_tot in (
                    1211, 1212, 1213, 1214, 1215, 1216, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1241, 1243, 1311, 1312, 1321, 1322, 1323,
                    1331, 1332, 1411, 1412, 1413, 1421, 1422, 1423, 1424, 1425, 1430, 2110, 2121, 2122, 2123, 2210, 2220, 2230, 2241, 2242, 2310, 2410, 
                    2420, 2430, 3112, 3113, 3114, 3116, 3120, 3130, 3231, 3232, 3331, 3332, 4110, 5111, 5112, 5113, 5114, 5123
                  )'  
          value: "'no_residents'"
          share: 0.5



