collection:
  # Overture release version
  version: 2025-01-22.0

  # Overture data theme
  theme: transportation

  # Overture type
  type: segment

  # Table in local database where data will be written
  local_result_table: temporal.segment_europe

  # A SQL query which returns the region's bounding geometry (omit terminating semicolon)
  # Leave this empty if global data is to be fetched
  region: "SELECT ST_Union(geom) AS geom FROM poi.geom_ref WHERE id = 'geofence_active_mobility'"
