collection:
  # Overture release version
  version: 2024-09-18.0

  # Overture data theme
  theme: divisions

  # Overture type
  type: division_area

  # Table in local database where data will be written
  local_result_table: temporal.division_area_all

  # A SQL query which returns the region's bounding geometry (omit terminating semicolon)
  # Leave this empty if global data is to be fetched
  region:
