preparation:
  start_date: "2022-12-06"
  num_weeks: 35
  network_dir: "eu"
  network_corrections: {
    "routes": "corrections_routes.txt"
  }
  target_schema: "gtfs"
  regions: "SELECT nuts_id as id, name, geom FROM public.nuts"
