preparation:
  start_date: "2025-02-04" # Must be a Tuesday for stop_times_optimized to be correct!
  num_weeks: 26
  network_dir: "eu"
  target_schema: "gtfs_eu"
  regions_query: "SELECT nuts_id, nuts_name FROM public.nuts WHERE cntr_code IN ('DE', 'DK', 'LU', 'NL', 'CH', 'AT', 'BE') AND levl_code = '3';"
