preparation:
  start_date: "2025-02-04" # Must be a Tuesday for stop_times_optimized to be correct!
  num_weeks: 26
  network_dir: "de"
  target_schema: "gtfs_de"
  regions_query: "SELECT nuts_id, nuts_name FROM public.nuts WHERE cntr_code IN ('DE') AND levl_code = '3';"
