region_pbf : [
    "https://download.geofabrik.de/europe/albania-latest.osm.pbf",
  "https://download.geofabrik.de/europe/andorra-latest.osm.pbf",
  #"https://download.geofabrik.de/europe/austria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/azores-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/belarus-latest.osm.pbf",
  #"https://download.geofabrik.de/europe/belgium-latest.osm.pbf",
  "https://download.geofabrik.de/europe/bosnia-herzegovina-latest.osm.pbf",
  "https://download.geofabrik.de/europe/bulgaria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/croatia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/cyprus-latest.osm.pbf",
  "https://download.geofabrik.de/europe/czech-republic-latest.osm.pbf",
  "https://download.geofabrik.de/europe/denmark-latest.osm.pbf",
  "https://download.geofabrik.de/europe/estonia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/faroe-islands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/finland-latest.osm.pbf",
#  "https://download.geofabrik.de/europe/france-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/georgia-latest.osm.pbf",
  #"https://download.geofabrik.de/europe/germany-latest.osm.pbf",
  "https://download.geofabrik.de/europe/greece-latest.osm.pbf",
  "https://download.geofabrik.de/europe/guernsey-jersey-latest.osm.pbf",
  "https://download.geofabrik.de/europe/hungary-latest.osm.pbf",
  "https://download.geofabrik.de/europe/iceland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/ireland-and-northern-ireland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf",
 # "https://download.geofabrik.de/europe/italy-latest.osm.pbf",
  "https://download.geofabrik.de/europe/kosovo-latest.osm.pbf",
  "https://download.geofabrik.de/europe/latvia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf",
  "https://download.geofabrik.de/europe/lithuania-latest.osm.pbf",  
  "https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf",
  "https://download.geofabrik.de/europe/macedonia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/malta-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/moldova-latest.osm.pbf",
  "https://download.geofabrik.de/europe/monaco-latest.osm.pbf",
  "https://download.geofabrik.de/europe/montenegro-latest.osm.pbf",
  #"https://download.geofabrik.de/europe/netherlands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/norway-latest.osm.pbf",
  "https://download.geofabrik.de/europe/poland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/portugal-latest.osm.pbf",
  "https://download.geofabrik.de/europe/romania-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/crimean-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/far-eastern-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/north-caucasus-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/northwestern-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/siberian-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/south-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/ural-fed-district-latest.osm.pbf",
  # "https://download.geofabrik.de/russia/volga-fed-district-latest.osm.pbf",
  "https://download.geofabrik.de/europe/serbia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/slovakia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/slovenia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/spain-latest.osm.pbf",
  "https://download.geofabrik.de/europe/sweden-latest.osm.pbf",
#  "https://download.geofabrik.de/europe/switzerland-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/turkey-latest.osm.pbf",
  # "https://download.geofabrik.de/europe/ukraine-latest.osm.pbf",
#  "https://download.geofabrik.de/europe/united-kingdom-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity: ["atm", "bank", "bar", "biergarten", "bicycle_parking", "bicycle_rental", "bus_station", "cafe", "car_sharing", "charging_station",
              "cinema", "dentist", "doctors", "fast_food", "fuel", "ice_cream", "kneipp_water_cure", "library",
              "marketplace", "nightclub", "pharmacy", "place_of_worship", "planetarium", "post_box", "post_office", "parking", "pub",
              "recycling", "restaurant", "taxi", "theatre", "vending_machine"]
    shop: ["bakery", "butcher", "chemist", "clothes", "convenience", "deli", "farm", "fashion", "florist", "fuel", "general",
           "greengrocer", "grocery", "hairdresser", "health_food", "honey", "kiosk", "mall", "shoes", "sports",
           "supermarket", "wine"]
    tourism: ["alpine_hut", "apartment", "aquarium", "camp_site", "caravan_site", "chalet", "gallery", "guest_house",
               "hostel", "hotel", "motel", "museum", "theme_park", "zoo"]
    railway: ["platform", "station", "stop", "subway_entrance", "tram_stop"]
    leisure: ["amusement_arcade", "disc_golf_course", "dog_park", "escape_game", "fitness_centre", "fitness_station",
              "miniature_golf", "playground", "sports_centre", "sports_hall", "swimming_area", "water_park"]
    sport: ["fitness", "swimming", "yoga"]
    highway: ["bus_stop"]
    public_transport: ["station", "stop_position"]
    historic: ["aircraft", "aqueduct", "archaeological_site", "battlefield", "bomb_crater", "castle", "church",
               "city_gate", "citywalls", "fort", "locomotive", "memorial", "monastery", "monument",
               "railway_car", "ruins", "ship", "tank", "tomb", "tower", "vehicle", "wreck"]

  additional_columns: ["name", "operator", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "email", "website", 
                       "capacity", "opening_hours", "wheelchair", "origin", "organic", "subway", "brand"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  convenience:
    classify_by_tag:
      other_grocery:
        shop: ["convenience"]

  deli:
    classify_by_tag:
      other_grocery:
        shop: ["deli"]
      
  greengrocer:
    classify_by_tag:
      other_grocery: 
        shop: ["greengrocer"]
  
validation:
  new_poi_table: "public.poi_osm_europe"
  old_poi_table:
    ["goat.poi_shopping","goat.poi_health","goat.poi_tourism_leisure","goat.poi_food_drink","goat.poi_mobility_service","goat.poi_public_service","goat.poi_service"]
  metrics:
    poi_count:
      geom_reference_query: "SELECT id , name , geom, 0 as population FROM goat.division_area_all_countries_and_territories"
      thresholds:
        absolute:
          positive: 4
          negative: -4
        relative:
          bakery: [-0.3, 0.3]
          butcher: [-0.3, 0.3]
          chemist: [-0.3, 0.3]
          discount_supermarket: [-0.3, 0.3]
          farm_shop: [-0.3, 0.3]
          food_vending_machine: [-0.3, 0.3]
          hypermarket: [-0.3, 0.3]
          marketplace: [-0.3, 0.3]
          organic_supermarket: [-0.3, 0.3]
          other_grocery: [-0.3, 0.3]
          supermarket: [-0.3, 0.3]
          winery: [-0.3, 0.3]
          dentist: [-0.3, 0.3]
          general_practitioner: [-0.3, 0.3]
          hospital: [-0.3, 0.3]
          pharmacy: [-0.3, 0.3]
      lower_bound: 3

   
subscription:
  repo_url: "https://github.com/plan4better/pois"
    