# List of all regions in Europe according to Geofabrik
region_pbf: [
  "https://download.geofabrik.de/europe/albania-latest.osm.pbf",
  "https://download.geofabrik.de/europe/andorra-latest.osm.pbf",
  "https://download.geofabrik.de/europe/austria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/azores-latest.osm.pbf",
  "https://download.geofabrik.de/europe/belarus-latest.osm.pbf",
  "https://download.geofabrik.de/europe/belgium-latest.osm.pbf",
  "https://download.geofabrik.de/europe/bosnia-herzegovina-latest.osm.pbf",
  "https://download.geofabrik.de/europe/bulgaria-latest.osm.pbf",
  "https://download.geofabrik.de/europe/croatia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/cyprus-latest.osm.pbf",
  "https://download.geofabrik.de/europe/czech-republic-latest.osm.pbf",
  "https://download.geofabrik.de/europe/denmark-latest.osm.pbf",
  "https://download.geofabrik.de/europe/estonia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/faroe-islands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/finland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/france-latest.osm.pbf",
  "https://download.geofabrik.de/europe/georgia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/germany-latest.osm.pbf",
  "https://download.geofabrik.de/europe/greece-latest.osm.pbf",
  "https://download.geofabrik.de/europe/guernsey-jersey-latest.osm.pbf",
  "https://download.geofabrik.de/europe/hungary-latest.osm.pbf",
  "https://download.geofabrik.de/europe/iceland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/ireland-and-northern-ireland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/isle-of-man-latest.osm.pbf",
  "https://download.geofabrik.de/europe/italy-latest.osm.pbf",
  "https://download.geofabrik.de/europe/kosovo-latest.osm.pbf",
  "https://download.geofabrik.de/europe/latvia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf",
  "https://download.geofabrik.de/europe/lithuania-latest.osm.pbf",
  "https://download.geofabrik.de/europe/luxembourg-latest.osm.pbf",
  "https://download.geofabrik.de/europe/macedonia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/malta-latest.osm.pbf",
  "https://download.geofabrik.de/europe/moldova-latest.osm.pbf",
  "https://download.geofabrik.de/europe/monaco-latest.osm.pbf",
  "https://download.geofabrik.de/europe/montenegro-latest.osm.pbf",
  "https://download.geofabrik.de/europe/netherlands-latest.osm.pbf",
  "https://download.geofabrik.de/europe/norway-latest.osm.pbf",
  "https://download.geofabrik.de/europe/poland-latest.osm.pbf",
  "https://download.geofabrik.de/europe/portugal-latest.osm.pbf",
  "https://download.geofabrik.de/europe/romania-latest.osm.pbf",
  ## "https://download.geofabrik.de/russia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/serbia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/slovakia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/slovenia-latest.osm.pbf",
  "https://download.geofabrik.de/europe/spain-latest.osm.pbf",
  "https://download.geofabrik.de/europe/sweden-latest.osm.pbf",
  "https://download.geofabrik.de/europe/switzerland-latest.osm.pbf",
  ## "https://download.geofabrik.de/europe/turkey-latest.osm.pbf",
  ## "https://download.geofabrik.de/europe/ukraine-latest.osm.pbf",
  "https://download.geofabrik.de/europe/united-kingdom-latest.osm.pbf",
]

collection:
  # Modes to be included in the collection
  modes: ['train', 'subway', 'monorail', 'tram', 'bus', 'trolleybus']

  # Path to an osm2pgsql style file
  osm2pgsql_style: "/app/src/config/osm_pt_lines.style"

preparation:
  # Prepration can produce multiple datasets - for eg. local services and regional services
  # Each dataset-mode may only specify "exclude_operators" or "include_operators", not both
  datasets:
    local:
      # Table in local database where data will be written
      local_result_table: temporal.osm_pt_lines_europe_local

      # Modes to be included in this dataset
      modes: ['subway', 'monorail', 'tram', 'bus', 'trolleybus']

      # Exclusion / inclusion criteria for each mode
      bus:
        exclude_operators: [
          'ALSA',
          'Arriva Bus',
          'Avanza',
          'Baltour',
          'BlaBlaCar Bus',
          'Bus Eireann',
          'Busabout',
          'Domo Reisen',
          'Ecolines',
          'Eurolines',
          'Eurolines/Isilinies',
          'FlixBus',
          'GoBus',
          'Interbus',
          'Karat-S',
          'LuxExpress',
          'Megabus',
          'National Express',
          'PolskiBus',
          'RegioJet',
          'Sindbad'
        ]
    regional:
      # Table in local database where data will be written
      local_result_table: temporal.osm_pt_lines_europe_regional

      # Modes to be included in this dataset
      modes: ['train', 'bus']

      # Exclusion / inclusion criteria for each mode
      bus:
        include_operators: [
          'ALSA',
          'Arriva Bus',
          'Avanza',
          'Baltour',
          'BlaBlaCar Bus',
          'Bus Eireann',
          'Busabout',
          'Domo Reisen',
          'Ecolines',
          'Eurolines',
          'Eurolines/Isilinies',
          'FlixBus',
          'GoBus',
          'Interbus',
          'Karat-S',
          'LuxExpress',
          'Megabus',
          'National Express',
          'PolskiBus',
          'RegioJet',
          'Sindbad'
        ]
