collection:
  # Overture data release version
  overture_release: "2023-12-14-alpha.0"

  # Must be a SQL query which returns the region's bounding geometry (omit terminating semicolon)
  geom_query: "SELECT geom
                FROM public.nuts
                WHERE levl_code = 0 AND cntr_code = 'DE'"

preparation:
  cycling_surfaces:
    pavingStones: '0.2'
    unpaved: '0.2'
    gravel: '0.3'
    dirt: '0.4'
