region_pbf : [
    "https://download.geofabrik.de/europe/germany/saarland-latest.osm.pbf" , 
    "https://download.geofabrik.de/europe/germany/rheinland-pfalz-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/baden-wuerttemberg-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/bayern-latest.osm.pbf", 
    "https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/sachsen-anhalt-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/thueringen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/mecklenburg-vorpommern-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hamburg-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/niedersachsen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/schleswig-holstein-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/nordrhein-westfalen-latest.osm.pbf",
    "https://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf"
]
collection:
  osm_tags:
    amenity : ["fuel", "taxi", "atm", "bank", "dentist", "doctors", "pharmacy", "post_box", "marketplace", "bar", "biergarten", "cafe", 
                "pub", "fast_food", "ice_cream", "restaurant", "theatre", "cinema", "library", "nightclub", "recycling", "car_sharing", "bicycle_rental", 
                "charging_station", "bus_station"]
    shop    : ["clothes", "convenience", "general", "fashion", "fuel", "bakery", "butcher", "florist", "greengrocer", "kiosk", "mall", "shoes", "sports", 
                "supermarket", "hairdresser", "health_food", "chemist", "ice_cream"]
    tourism : ["hotel", "museum", "hostel", "guest_house"]
    railway : ["station", "platform", "stop", "tram_stop", "subway_entrance"]
    leisure : ["playground", "fitness_station", "water_park", "pitch", "sports_centre", 'sports_hall', "fitness_centre"]
    sport   : ["yoga", "fitness"]
    highway : ["bus_stop"]
    public_transport : ["stop_position", "station"]

  additional_columns: ["name", "brand", "addr:street","addr:housenumber", "addr:postcode", "addr:city", "addr:country", "phone", "website", 
                        "opening_hours", "operator", "origin", "organic", "subway"]
  nodes : True
  ways : True
  relations : True
  
preparation:
  supermarket:
    classify_by_name:
      supermarket: 
        string_similarity: 
          children:
            rewe     : ["rewe", "rewe city"]
            tegut    : ["tegut"]
            feneberg : ["feneberg"]
            nahkauf  : ["nahkauf"]
            kupsch   : ["kupsch"]
            aez      : ["aez"]
            edeka    : ["edeka", "nah & gut", "e center", "diska"]
            k+k      : ["k+k", "k&k"]
            nah&frisch : ["nah&frisch"]
          threshold: 0.7

      discount_supermarket: 
        string_similarity: 
          children:
            aldi  : ["aldi"]
            lidl  : ["lidl"]
            netto : ["netto"]
            norma : ["norma"]
            penny : ["penny"]
            np-markt: ["np markt"]
          threshold: 0.7
        exact_match:
          children:
            np-markt : ["np"]

      hypermarket: 
        string_similarity:
          children:
            real      : ["real"]
            v-markt   : ["v-markt"]
            kaufland  : ["kaufland"]
            marktkauf : ["marktkauf"]
            hit       : ["hit"]
          threshold: 0.7

      wholesale: 
        string_similarity:
          children:
            metro     : ["metro"]
            hamberger : ["hamberger"]
          threshold: 0.7
      
      organic_supermarket:
        string_similarity:
          children:
            denn's Biomarkt : ["denn's", "denns", "denn"]
            alnatura : ["alnatura"]
            vollcorner : ["vollcorner"]
            reformhaus : ["reformhaus"]
            naturkost : ["naturkost"]
            bio: ["bio"]
          threshold: 0.7
      
      international_supermarket:
        string_similarity:
          children:
            turkish : ["türkisch", "turk"]
            asia : ["asia"]
            mix market : ["mix market"]
          threshold: 0.7

    classify_by_tag:
      international_supermarket:
        origin: True 
      organic_supermarket:
        organic: "only"

  chemist: 
    string_similarity:
      children:
        rossmann : ["rossmann"]
        müller   : ["müller", "mueller"] 
      threshold: 0.7
    exact_match:
      children:
        dm       : ["dm"]


  health_food: 
    string_similarity:
      children:
        vitalia   : ["vitalia"]
        reformhaus : ["reformhaus"]
      threshold: 0.7

  bank: 
    sparkasse       : ["kreissparkasse", "sparkasse", "stadtsparkasse"]
    raiffeisenbank  : ["raiffeisenbank", "vr bank", "vr-bank", "volksbank", "volks", "münchner"]
    hypovereinsbank : ["hypo vereinsbank", "hypovereinsbank"]
    commerzbank : ["commerzbank"]



  fast_food: 
    mcdonalds : ["mcdonald"]

  discount_gym: 
    fitx           : ["fitx"]
    mcfit          : ["mcfit"]
    fitstar        : ["fitstar","fit-star", "fit star"]
    cleverfit      : ["cleverfit" ,"clever fit"]
    jumpersfitness : ["jumpersfitness" ,"jumpers fitness"]

  community_sport_centre: ["bezirkssportanlage"]

  # Not used (operators for various cities in Germany are too different)
  operators_bicycle_rental: ["münchner verkehrs gesellschaft", "münchner verkehrsgesellschaft", "mvg"]

  sport:
    sport_var_disc   : ["table_tennis"]
    leisure_var_add  : ["sports_hall", "fitness_center", "sport_center", "track", "pitch"]
    leisure_var_disc : ["fitness_station"]
    